import os
import codecs
import json
import traceback

filepath = r'c:\Users\Mahir\Desktop\Locy\locales\translations.js'

with codecs.open(filepath, 'r', 'utf-8') as f:
    text = f.read()

start = text.find('{')
end = text.rfind('}') + 1
json_string = text[start:end]

try:
    data = json.loads(json_string)
except Exception as e:
    print("Failed to parse JSON directly:", e)
    # If JSON parsing fails due to JS syntax like unquoted keys or trailing commas, we could use a custom regex patch.
    # We will print the error for fallback decision.
    traceback.print_exc()
    import sys
    sys.exit(1)

translations = {
    'de': {
        "footer_link_trust": "Trust Center",
        "comp_btn_trust": "Trust Center ansehen",
        "comp_btn_sales": "Vertrieb (Compliance)",
        "terms_h4": "4. Service Level Agreement (SLA) & Richtlinien",
        "terms_p4_2": "<strong>SLA-Gutschriften:</strong> Fällt die monatliche Uptime unter 99,9%, erhalten Enterprise-Kunden SLA Gutschriften.",
        "terms_p4_3": "<strong>Haftungsbeschränkung:</strong> ThinkPoint OÜ haftet in keinem Fall für indirekte betriebliche Verluste.",
        "terms_p4_4": "<strong>Kündigung:</strong> Standard-Pläne können jederzeit gekündigt werden.",
        "product_secd_title": "Das gesamte Team stärken.",
        "product_secd_desc": "Vom Kurier bis zum CTO-Dashboard.",
        "product_persona1_title": "Betriebsleiter (Ops)",
        "product_persona1_desc": "Sichtbarkeit erhöhen. Eliminieren Sie ständige Anrufe. Locy standardisiert die chaotische letzte Meile.",
        "product_persona2_title": "IT & Engineering",
        "product_persona2_desc": "Integration in Minuten. Unsere API ist zustandslos. <strong>Limits:</strong> Dynamic Sequencing ist auf 25 Stopps pro Anfrage begrenzt, um subsekundenschnelle Reaktionen zu garantieren.",
        "rest_kpi_1": "↓ 30% weniger Fahrer-Anrufe",
        "eco_kpi_1": "↑ 15% Erstzustellungsquote",
        "eco_privacy_note": "* Keine Datenspeicherung. Standort verifiziert, ohne Routen aufzuzeichnen.",
        "em_kpi_1": "↓ 2,5 Min. Reaktionszeit gespart",
        "em_compliance_link": "Globalen Compliance-Anhang ansehen &rarr;",
        "pricing_card2_cta": "API-Schlüssel holen & Checkout",
        "pricing_card3_cta": "Pilot-Demo planen",
        "pricing_roi_title": "Die Mathematik der Marge",
        "pricing_roi_desc": "Locy ist so bepreist, dass es immer günstiger ist, als manuelles Tippen und Fahrerverzögerungen.",
        "pricing_roi_del": "Lieferungen / Monat",
        "pricing_roi_time": "Gesparte Zeit pro Lieferung",
        "pricing_roi_rec": "Zurückgewonnene Arbeitsstunden",
        "pricing_roi_note": "* Berechnet auf Basis durchschnittlicher Verzögerungen beim Tippen.",
        "priv_h2_5": "2.5 Datenkategorien & Aufbewahrung",
        "priv_tab_cat": "Datenkategorie",
        "priv_tab_purp": "Zweck",
        "priv_tab_ret": "Aufbewahrungsfrist",
        "priv_tab_d1": "Paketbilder",
        "priv_tab_p1": "Koordinatenextraktion",
        "priv_tab_r1": "0 Sekunden (Sofort gelöscht)",
        "priv_tab_d2": "WhatsApp Telefonnummern",
        "priv_tab_p2": "API-Routing & Support",
        "priv_tab_r2": "30 Tage (Systemprotokolle)",
        "priv_tab_d3": "Rechnungs-Tokens",
        "priv_tab_p3": "Fakturierung",
        "priv_tab_r3": "Gesetzlich (Bis zu 7 Jahre)",
        "priv_trust_link": "Besuchen Sie unser Trust Center für DPA und Subunternehmer &rarr;",
        "trust_title": "Trust Center",
        "trust_desc": "Sicherheit, Compliance und Transparenz auf Enterprise-Niveau.",
        "trust_dpa_title": "Auftragsverarbeitungsvertrag (AVV/DPA)",
        "trust_dpa_desc": "Unser Standard-AVV entspricht der DSGVO. Fordern Sie eine unterzeichnete Kopie an.",
        "trust_dpa_btn": "AVV anfragen",
        "trust_pack_title": "Sicherheits- & Compliance-Paket",
        "trust_pack_desc": "Laden Sie unsere Sicherheitsarchitektur-Übersicht herunter.",
        "trust_pack_btn": "PDF herunterladen",
        "trust_diag_title": "Datenlebenszyklus-Architektur",
        "trust_diag_desc": "Locys zustandslose Engine gewährleistet Zero-Retention. So fließt ein Bild:",
        "trust_sub_title": "Autorisierte Unterauftragnehmer",
        "trust_sub_desc": "Um Dienste weltweit mit geringer Latenz bereitzustellen, nutzen wir die folgenden Anbieter.",
        "trust_tab_entity": "Unternehmensname",
        "trust_tab_purpose": "Zweck",
        "trust_tab_location": "Standort",
        "trust_tab_p1": "Cloud-Infrastruktur & API-Hosting",
        "trust_tab_p2": "WhatsApp Cloud API Anbieter",
        "trust_tab_p3": "Vision-Modelle (Zero-Retention API)",
        "trust_sub_note": "* Locy verwendet Enterprise Vision APIs ohne KI Trainingsdaten."
    },
    'fr': {
        "footer_link_trust": "Centre de Confiance",
        "comp_btn_trust": "Voir le Centre de Confiance",
        "comp_btn_sales": "Contacter les Ventes",
        "terms_h4": "4. Accord de Niveau de Service (SLA)",
        "terms_p4_2": "<strong>Crédits SLA :</strong> Crédits de service disponibles.",
        "terms_p4_3": "<strong>Limitation de Responsabilité :</strong> ThinkPoint OÜ n'est en aucun cas responsable des pertes d'exploitation indirectes.",
        "terms_p4_4": "<strong>Annulation :</strong> Les forfaits standards peuvent être annulés à tout moment.",
        "product_secd_title": "Renforcer Toute l'Équipe.",
        "product_secd_desc": "Du pouce du coursier au tableau de bord.",
        "product_persona1_title": "Directeur des Opérations",
        "product_persona1_desc": "Obtenez une visibilité à 100%. Éliminez les appels répétitifs. Locy standardise le dernier kilomètre.",
        "product_persona2_title": "IT & Ingénierie",
        "product_persona2_desc": "Une intégration en quelques minutes. Notre API est strictement sans état. <strong>Limites :</strong> Le séquençage dynamique est limité à 25 arrêts.",
        "rest_kpi_1": "↓ 30% de réduction des appels",
        "eco_kpi_1": "↑ 15% de succès de livraison",
        "eco_privacy_note": "* Aucune conservation des données.",
        "em_kpi_1": "↓ 2,5 min gagnées en temps",
        "em_compliance_link": "Voir notre Annexe de Conformité &rarr;",
        "pricing_card2_cta": "Obtenir la Clé API",
        "pricing_card3_cta": "Planifier une Démo Pilote",
        "pricing_roi_title": "La Mathématique de la Marge",
        "pricing_roi_desc": "Locy est conçu pour toujours rester moins cher.",
        "pricing_roi_del": "Livraisons / Mois",
        "pricing_roi_time": "Temps gagné",
        "pricing_roi_rec": "Heures récupérées",
        "pricing_roi_note": "* Calculé sur la base des retards moyens.",
        "priv_h2_5": "2.5 Catégories de Données",
        "priv_tab_cat": "Catégorie de Données",
        "priv_tab_purp": "Objectif",
        "priv_tab_ret": "Période de Rétention",
        "priv_tab_d1": "Images de Colis",
        "priv_tab_p1": "Extraction de coordonnées",
        "priv_tab_r1": "0 Secondes (Immédiate)",
        "priv_tab_d2": "Numéros WhatsApp",
        "priv_tab_p2": "Routage API & Support",
        "priv_tab_r2": "30 Jours (Logs système)",
        "priv_tab_d3": "Tokens de Facturation",
        "priv_tab_p3": "Facturation",
        "priv_tab_r3": "Statutaire (Jusqu'à 7 ans)",
        "priv_trust_link": "Visitez notre Centre de Confiance &rarr;",
        "trust_title": "Centre de Confiance",
        "trust_desc": "Sécurité, conformité et transparence de niveau Entreprise.",
        "trust_dpa_title": "Accord de Traitement des Données (DPA)",
        "trust_dpa_desc": "Notre DPA standard est conforme au RGPD. Demandez une copie.",
        "trust_dpa_btn": "Demander le DPA",
        "trust_pack_title": "Pack de Sécurité & Conformité",
        "trust_pack_desc": "Téléchargez l'aperçu de l'architecture de sécurité.",
        "trust_pack_btn": "Télécharger le PDF",
        "trust_diag_title": "Architecture du Cycle de Vie",
        "trust_diag_desc": "Rétention zéro. Voici comment une image circule :",
        "trust_sub_title": "Sous-traitants Autorisés",
        "trust_sub_desc": "Nous collaborons avec les fournisseurs suivants, soumis à des accords DPA stricts.",
        "trust_tab_entity": "Nom de l'Entité",
        "trust_tab_purpose": "Objectif",
        "trust_tab_location": "Emplacement",
        "trust_tab_p1": "Infrastructure Cloud",
        "trust_tab_p2": "Fournisseur API WhatsApp",
        "trust_tab_p3": "Modèles de Vision",
        "trust_sub_note": "* Locy utilise des API sans entraînement de données."
    },
    'es': {
        "footer_link_trust": "Centro de Confianza",
        "comp_btn_trust": "Ver Centro de Confianza",
        "comp_btn_sales": "Contactar Ventas",
        "terms_h4": "4. Acuerdo de Nivel de Servicio (SLA)",
        "terms_p4_2": "<strong>Créditos SLA:</strong> Créditos por interrupciones operativas.",
        "terms_p4_3": "<strong>Límite de Responsabilidad:</strong> Responsabilidad técnica limitada.",
        "terms_p4_4": "<strong>Cancelación:</strong> Los planes estándar se pueden cancelar en cualquier momento.",
        "product_secd_title": "Empoderando al Equipo.",
        "product_secd_desc": "Desde el pulgar del repartidor hasta el CTO.",
        "product_persona1_title": "Gerentes de Operaciones",
        "product_persona1_desc": "Obtenga visibilidad del 100%. Elimine llamadas repetitivas.",
        "product_persona2_title": "Desarrollo y Sistemas",
        "product_persona2_desc": "Integración en minutos. <strong>Límites:</strong> Rutas limitadas a 25 paradas.",
        "rest_kpi_1": "↓ 30% reducción de llamadas de conductores",
        "eco_kpi_1": "↑ 15% Éxito de entrega",
        "eco_privacy_note": "* Cero retención. Ubicaciones verificadas sin guardar rutas.",
        "em_kpi_1": "↓ 2.5 min de tiempo ahorrado",
        "em_compliance_link": "Ver Anexo de Cumplimiento &rarr;",
        "pricing_card2_cta": "Obtener la API",
        "pricing_card3_cta": "Solicitar Demo",
        "pricing_roi_title": "La Matemática del Margen",
        "pricing_roi_desc": "Locy es siempre más barato que el costo de la escritura manual.",
        "pricing_roi_del": "Entregas / Mes",
        "pricing_roi_time": "Tiempo ahorrado",
        "pricing_roi_rec": "Horas operativas ahorradas",
        "pricing_roi_note": "* Basado en demoras promedio.",
        "priv_h2_5": "2.5 Datos y Retención",
        "priv_tab_cat": "Categoría de Datos",
        "priv_tab_purp": "Propósito",
        "priv_tab_ret": "Período de Retención",
        "priv_tab_d1": "Imágenes de Paquetes",
        "priv_tab_p1": "Extracción de coordenadas",
        "priv_tab_r1": "0 Segundos",
        "priv_tab_d2": "Números WhatsApp",
        "priv_tab_p2": "Enrutamiento API y Soporte",
        "priv_tab_r2": "30 Días",
        "priv_tab_d3": "Facturación",
        "priv_tab_p3": "Facturación",
        "priv_tab_r3": "Hasta 7 años",
        "priv_trust_link": "Visita nuestro Centro de Confianza &rarr;",
        "trust_title": "Centro de Confianza",
        "trust_desc": "Seguridad, cumplimiento y transparencia para empresas.",
        "trust_dpa_title": "Acuerdo de Procesamiento de Datos (DPA)",
        "trust_dpa_desc": "Nuestro DPA cumple con el RGPD. Solicite una copia contrafirmada.",
        "trust_dpa_btn": "Solicitar DPA",
        "trust_pack_title": "Paquete de Seguridad",
        "trust_pack_desc": "Descargue la arquitectura de seguridad.",
        "trust_pack_btn": "Descargar PDF",
        "trust_diag_title": "Arquitectura de Datos",
        "trust_diag_desc": "La API sin estado garantiza que no haya retención de datos:",
        "trust_sub_title": "Subprocesadores Autorizados",
        "trust_sub_desc": "Nuestros proveedores líderes cumplen acuerdos estrictos.",
        "trust_tab_entity": "Nombre de Entidad",
        "trust_tab_purpose": "Propósito",
        "trust_tab_location": "Ubicación",
        "trust_tab_p1": "Infraestructura Cloud",
        "trust_tab_p2": "Proveedor WhatsApp API",
        "trust_tab_p3": "Modelos de Visión",
        "trust_sub_note": "* Usamos API de visión empresarial sin entrenamientos basados en el cliente."
    },
    'et': {
        "footer_link_trust": "Usalduskeskus",
        "comp_btn_trust": "Vaata Usalduskeskust",
        "comp_btn_sales": "Võta Ühendust",
        "terms_h4": "4. Teenusetaseme Leping (SLA)",
        "terms_p4_2": "<strong>SLA:" "</strong> Kui tegevusaeg langeb.",
        "terms_p4_3": "<strong>Vastutuse Piirang:" "</strong> ThinkPoint OÜ ei vastuta defektide eest.",
        "terms_p4_4": "<strong>Tühistamine:" "</strong> Standard-paketid.",
        "product_secd_title": "Sujuv Tööpäev.",
        "product_secd_desc": "Kullerite ekraanilt juhtide statistikasse.",
        "product_persona1_title": "Operatsioonijuhid",
        "product_persona1_desc": "Saage 100% ülevaade marsruutidest. Locy tagab kohalejõudmise.",
        "product_persona2_title": "IT & Insenerid",
        "product_persona2_desc": "Seadistage minutitega. Dynamic Sequencing piirang 25 asukohta.",
        "rest_kpi_1": "↓ 30% vähem kõnesid klientidele",
        "eco_kpi_1": "↑ 15% Paki Esmane Kohaletoimetamine",
        "eco_privacy_note": "* Andmete säilitamine puudub. Asukoht turvatud.",
        "em_kpi_1": "↓ 2,5 min keskmiselt võidetud aega",
        "em_compliance_link": "Vaata Lisainfot &rarr;",
        "pricing_card2_cta": "Telli Standard Pakett",
        "pricing_card3_cta": "Broneeri Demo",
        "pricing_roi_title": "ROI Arvutus",
        "pricing_roi_desc": "Locy säästab raha igal pakil.",
        "pricing_roi_del": "Kulleritellimused",
        "pricing_roi_time": "Võit ajas",
        "pricing_roi_rec": "Kokkuhoitud Tunnid",
        "pricing_roi_note": "* Arvestatud andmete sisestusest ajendatud defektidel.",
        "priv_h2_5": "2.5 Andmekategooriad",
        "priv_tab_cat": "Kategooria",
        "priv_tab_purp": "Eesmärk",
        "priv_tab_ret": "Säilitusaeg",
        "priv_tab_d1": "Piltide ja Pakiinfo",
        "priv_tab_p1": "Aadresside otsing",
        "priv_tab_r1": "0 Sekundit",
        "priv_tab_d2": "WhatsApp Numbid",
        "priv_tab_p2": "Toetav Infosüsteem",
        "priv_tab_r2": "30 Päeva",
        "priv_tab_d3": "Maksedetailid",
        "priv_tab_p3": "Arveldamine",
        "priv_tab_r3": "Kuni 7 Aastat",
        "priv_trust_link": "Tutvu Usalduskeskusega &rarr;",
        "trust_title": "Usalduskeskus",
        "trust_desc": "Andmekaitse, vastavusreeglid ja turvalisus.",
        "trust_dpa_title": "Andmetöötlusleping (DPA)",
        "trust_dpa_desc": "Meie DPA on kooskõlas Euroopa Liidu isikuandmete kaitse üldmäärusega.",
        "trust_dpa_btn": "Küsi DPA",
        "trust_pack_title": "Andmekaitse Dokumentatsioon",
        "trust_pack_desc": "Laadige alla meie detailne süsteemiarhitektuur.",
        "trust_pack_btn": "Lae PDF",
        "trust_diag_title": "Struktuur",
        "trust_diag_desc": "Sõlmede loogika on ilma säilitamiseta.",
        "trust_sub_title": "Luba Omavad Koostööpartnerid",
        "trust_sub_desc": "Teeme koostööd järgmiste ettevõtetega.",
        "trust_tab_entity": "Nimi",
        "trust_tab_purpose": "Eesmärk",
        "trust_tab_location": "Asukoht",
        "trust_tab_p1": "Pilveteenus",
        "trust_tab_p2": "WhatsApp App",
        "trust_tab_p3": "AI Server",
        "trust_sub_note": "* Andmete treenimine lahenduses ei toimu."
    },
    'it': {
        "footer_link_trust": "Centro Fiduciario",
        "comp_btn_trust": "Vedi il Centro Fiduciario",
        "comp_btn_sales": "Contatta le Vendite",
        "terms_h4": "4. Service Level Agreement (SLA)",
        "terms_p4_2": "<strong>Crediti SLA:</strong> Clienti Enterprise.",
        "terms_p4_3": "<strong>Limitazione di Responsabilità:</strong> ThinkPoint OÜ.",
        "terms_p4_4": "<strong>Cancellazione:</strong> Cancellare i piani standard.",
        "product_secd_title": "Efficienza per tutto il Team.",
        "product_secd_desc": "Dallo schermo del driver alla dashboard tecnica.",
        "product_persona1_title": "Team Operativo",
        "product_persona1_desc": "Visibilità completa delle operazioni. Locy standardizza l'ultimo miglio.",
        "product_persona2_title": "Tecnica & IT",
        "product_persona2_desc": "Limiti: Dynamic Sequencing è limitato a 25.",
        "rest_kpi_1": "↓ 30% di chiamate ridotte",
        "eco_kpi_1": "↑ 15% di consegne completate",
        "eco_privacy_note": "* Nessuna memorizzazione delle posizioni del corriere.",
        "em_kpi_1": "↓ 2.5 min risparmiati",
        "em_compliance_link": "Visualizza Documento &rarr;",
        "pricing_card2_cta": "Ottieni API",
        "pricing_card3_cta": "Demo",
        "pricing_roi_title": "Ritorno sugli Investimenti",
        "pricing_roi_desc": "Meno costi dal lavoro manuale.",
        "pricing_roi_del": "Consegne/Mese",
        "pricing_roi_time": "Tempo risparmiato",
        "pricing_roi_rec": "Ore operative salvate",
        "pricing_roi_note": "* Calcolato su base statistica.",
        "priv_h2_5": "2.5 Categorie di Dati & Ritenzioni",
        "priv_tab_cat": "Categoria",
        "priv_tab_purp": "Scopo",
        "priv_tab_ret": "Periodo",
        "priv_tab_d1": "Immagini",
        "priv_tab_p1": "Estrazione Coordinate",
        "priv_tab_r1": "0 Secondi",
        "priv_tab_d2": "Numeri WhatsApp",
        "priv_tab_p2": "Inoltro e API",
        "priv_tab_r2": "30 Giorni",
        "priv_tab_d3": "Fatturazione",
        "priv_tab_p3": "Fatture",
        "priv_tab_r3": "7 Anni Diritto",
        "priv_trust_link": "Vedi l'Area DPA nel Trust Center &rarr;",
        "trust_title": "Centro Fiduciario",
        "trust_desc": "Controllo sicurezza.",
        "trust_dpa_title": "Data Processing Agreement",
        "trust_dpa_desc": "Contratto GDPR.",
        "trust_dpa_btn": "Richiedi DPA",
        "trust_pack_title": "Toolkit di Sicurezza",
        "trust_pack_desc": "Risultati IT.",
        "trust_pack_btn": "Download PDF",
        "trust_diag_title": "Analisi del Flusso senza Conservazione",
        "trust_diag_desc": "Zero conservazione:",
        "trust_sub_title": "Subprocessatori Incaricati",
        "trust_sub_desc": "Altre aziende:",
        "trust_tab_entity": "Azienda",
        "trust_tab_purpose": "Sviluppo Base",
        "trust_tab_location": "Stato ",
        "trust_tab_p1": "AWS Cloud IT",
        "trust_tab_p2": "Rete WhatsApp",
        "trust_tab_p3": "Modelli Generativi",
        "trust_sub_note": "* Nessun addestramento dati."
    }
}

for lang in translations:
    for k, v in translations[lang].items():
        data[lang][k] = v

json_fixed = json.dumps(data, indent=2, ensure_ascii=False)
final_text = text[:start] + json_fixed + "\n" + text[end:]

with codecs.open(filepath, 'w', 'utf-8') as f:
    f.write(final_text)

print("Parsed and updated EU translations successfully.")
