import re
import json

new_data = {
    "de": {
        "pricing_hero_sub": "NUTZUNGSBASIERTE PREISE",
        "pricing_hero_title": "Bezahlen Sie nur für gültige <span class=\"text-gradient\">Koordinaten.</span><br>Sonst nichts.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "Für Tests und kleine Pilotprojekte.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 Abfragen / Monat",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Multimodale KI-Engine",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Community-Support",
        "pricing_card1_cta": "Kostenlos starten",
        "pricing_card2_badge": "BELIEBTESTE",
        "pricing_card2_title": "Standard",
        "pricing_card2_desc": "Nutzungsbasiertes Modell.",
        "pricing_card2_price": "$0.05 <span>/ Abfrage</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Unbegrenzte Abfragen",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Priorisierte Warteschlange",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Routenoptimierung inklusive",
        "pricing_card2_cta": "Jetzt Loslegen",
        "pricing_card3_title": "Enterprise",
        "pricing_card3_desc": "Für große Flotten.",
        "pricing_card3_price": "Individuell",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Mengenrabatte",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Persönlicher Betreuer",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 99.9% SLA-Garantie",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 24/7 Support",
        "pricing_card3_cta": "Vertrieb Kontaktieren",
        "pricing_faq_title": "Häufige Fragen",
        "pricing_faq1_q": "Werden die Bilder gespeichert?",
        "pricing_faq1_a": "Nein. Locy arbeitet ohne Datenspeicherung. Bilder werden im flüchtigen Speicher verarbeitet und nach der Koordinatenextraktion sofort gelöscht. Wir trainieren keine Modelle mit Ihren Daten.",
        "pricing_faq2_q": "Was zählt als eine 'Abfrage' (Look)?",
        "pricing_faq2_a": "Eine 'Abfrage' ist jede erfolgreiche API-Anfrage oder WhatsApp-Nachricht, die eine gültige Koordinate oder Route zurückgibt. Fehler und unklare Ergebnisse werden nicht berechnet.",
        "pricing_faq3_q": "Gibt es ein Volumenlimit?",
        "pricing_faq3_a": "Der Standard-Tarif unterstützt bis zu 10 Anfragen pro Sekunde (RPS). Für einen höheren Durchsatz kontaktieren Sie bitte den Enterprise-Vertrieb für dedizierte Server.",
        "pricing_faq4_q": "Kann ich die Koordinaten speichern (cachen)?",
        "pricing_faq4_a": "Ja. Sobald Sie für die Daten bezahlen, gehören sie Ihnen. Sie können die Koordinaten unbegrenzt zwischenspeichern und wiederverwenden.",
        "product_hero_sub": "FÜR FAHRER UND FLOTTEN",
        "product_hero_title": "Schreiben Sie keine <span class=\"text-gradient\">Adressen mehr.</span>",
        "product_hero_desc": "Das Werkzeug, das Fahrer lieben. Adressen nicht mehr manuell eingeben. Einfach an WhatsApp weiterleiten. Überprüfung in Millisekunden.",
        "product_seca_title": "Einfach ein Foto machen. <br>Wir erledigen den Rest.",
        "product_seca_desc": "Fahrer sollten keine Datenerfasser sein. Locy liest selbst die unordentlichste Handschrift.<br><br>Unsere KI extrahiert Adressen von Frachtbriefen, Notizen und Etiketten. Sie fahren einfach.",
        "product_card_res": "Analyseergebnis",
        "product_card_ver": "ÜBERPRÜFT 99.9%",
        "product_card_det": "Erfasste Adresse",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Koordinaten",
        "product_card_ctx": "Kontext",
        "product_card_ctx_1": "Gewerblich",
        "product_card_ctx_2": "Haupteingang",
        "product_secb_title": "Punktgenaue Überprüfung.",
        "product_secb_desc": "Wir raten nicht. Wir überprüfen.",
        "product_feat1_title": "Nie wieder verfahren",
        "product_feat1_desc": "Adressen werden mit Geo-Datenbanken abgeglichen. Wir liefern verifizierte Längen-/Breitengrade, damit Sie direkt vor die Tür fahren.",
        "product_feat2_title": "Dynamische Sequenzierung",
        "product_feat2_desc": "Senden Sie 25 Stopps. Erhalten Sie 1 optimale Route. Beenden Sie Ihre Tour schneller mit KI-gestützter Routenoptimierung.",
        "product_feat3_title": "Sofortige Antwort",
        "product_feat3_desc": "Für Geschwindigkeit gebaut. Vom Bild-Upload bis zur Routengenerierung in unter einer Sekunde.",
        "product_secc_title": "Erweiterte Fahrerfunktionen.",
        "product_secc_desc": "Entwickelt für die Realitäten der Straße.",
        "product_feat4_title": "One-Tap Routenumkehr",
        "product_feat4_desc": "Möchten Sie Ihre Route rückwärts beginnen? Tippen Sie auf 'Route umkehren' in WhatsApp. Die Optimierung wird sofort von hinten nach vorne (LIFO) neu erstellt.",
        "product_feat5_title": "Pin-zu-Text",
        "product_feat5_desc": "In einer ländlichen Gegend verirrt? Senden Sie Ihren GPS-Pin an Locy. In Sekunden erhalten Sie die genaue Hausnummer und Adresse als Text. Eine Branchenneuheit.",
        "product_feat6_title": "Stiller Verlustschutz",
        "product_feat6_desc": "Wenn 1 von 20 Adressen unleserlich ist, stürzt das System nicht ab. Es routet die 19 guten Adressen und listet die 1 unlesbare separat auf.",
        "product_feat7_title": "Live-Disponent",
        "product_feat7_desc": "Locy liefert Live-Tippaktualisierungen ('Lese...', 'Suche Koordinaten...'), sobald Sie ein Foto senden. Es fungiert als Ihr virtueller Echtzeit-Disponent.",
        "product_cta_title": "Bereit zum Start?",
        "product_cta_desc": "Keine Kreditkarte erforderlich. Beginnen Sie noch heute mit der Optimierung."
    },
    "fr": {
        "pricing_hero_sub": "PRIX À L'UTILISATION",
        "pricing_hero_title": "Payez pour des <span class=\"text-gradient\">coordonnées</span> valides.<br>Rien d'autre.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "Pour les tests et petits pilotes.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 requêtes / mois",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Moteur IA Multimodal",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Support Communautaire",
        "pricing_card1_cta": "Démarrer gratuitement",
        "pricing_card2_badge": "LE PLUS POPULAIRE",
        "pricing_card2_title": "Standard",
        "pricing_card2_desc": "Paiement à l'usage.",
        "pricing_card2_price": "$0.05 <span>/ requête</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Requêtes illimitées",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> File d'attente prioritaire",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Optimisation d'itinéraire incluse",
        "pricing_card2_cta": "Commencer",
        "pricing_card3_title": "Entreprise",
        "pricing_card3_desc": "Pour les grandes flottes.",
        "pricing_card3_price": "Sur mesure",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Remises sur volume",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Responsable dédié",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Garantie SLA 99.9%",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Support 24/7",
        "pricing_card3_cta": "Contacter les ventes",
        "pricing_faq_title": "Questions fréquentes",
        "pricing_faq1_q": "Conservez-vous les images ?",
        "pricing_faq1_a": "Non. Locy fonctionne sans rétention. Les images sont traitées en mémoire volatile et supprimées immédiatement. Nous n'utilisons pas vos données pour entraîner nos modèles.",
        "pricing_faq2_q": "Qu'est-ce qu'une 'requête' (Look) ?",
        "pricing_faq2_a": "Une 'requête' est un message WhatsApp ou API réussi qui renvoie une coordonnée ou un itinéraire valide. Les erreurs ne sont pas facturées.",
        "pricing_faq3_q": "Y a-t-il une limite de volume ?",
        "pricing_faq3_a": "Le forfait Standard prend en charge jusqu'à 10 requêtes par seconde (RPS). Pour un débit plus élevé, veuillez contacter les ventes Entreprise.",
        "pricing_faq4_q": "Puis-je mettre les coordonnées en cache ?",
        "pricing_faq4_a": "Oui. Une fois que vous payez pour les données, elles vous appartiennent. Vous pouvez stocker et réutiliser les coordonnées indéfiniment.",
        "product_hero_sub": "POUR LES CHAUFFEURS ET LES FLOTTES",
        "product_hero_title": "Arrêtez de taper des <span class=\"text-gradient\">adresses.</span>",
        "product_hero_desc": "L'outil que les chauffeurs adorent. Ne saisissez plus les adresses manuellement. Transférez simplement sur WhatsApp. Vérification en quelques millisecondes.",
        "product_seca_title": "Prenez une photo. <br>Nous faisons le reste.",
        "product_seca_desc": "Notre IA ingère les manifestes, les notes et les étiquettes, détectant automatiquement les points de livraison. Vous n'avez qu'à conduire.",
        "product_card_res": "Résultat d'analyse",
        "product_card_ver": "VÉRIFIÉ 99.9%",
        "product_card_det": "Adresse détectée",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Coordonnées",
        "product_card_ctx": "Contexte",
        "product_card_ctx_1": "Commercial",
        "product_card_ctx_2": "Entrée Principale",
        "product_secb_title": "Vérification précise.",
        "product_secb_desc": "Nous ne devinons pas. Nous vérifions.",
        "product_feat1_title": "Ne vous perdez jamais",
        "product_feat1_desc": "Nous renvoyons des coordonnées Lat/Long vérifiées afin que vous alliez directement à la porte.",
        "product_feat2_title": "Séquençage dynamique",
        "product_feat2_desc": "Soumettez 25 arrêts. Recevez 1 itinéraire optimal. Terminez votre tournée plus rapidement.",
        "product_feat3_title": "Réponse instantanée",
        "product_feat3_desc": "Conçu pour la vitesse. Du téléchargement de l'image à la génération de l'itinéraire en moins d'une seconde.",
        "product_secc_title": "Fonctions avancées pour le conducteur.",
        "product_secc_desc": "Conçu pour les réalités de la route.",
        "product_feat4_title": "Itinéraire inversé en un clic",
        "product_feat4_desc": "Appuyez sur 'Inverser' dans WhatsApp. L'optimisation est recréée instantanément de la fin au début (LIFO).",
        "product_feat5_title": "Pin-to-Text",
        "product_feat5_desc": "Partagez votre position GPS actuelle et recevez le numéro de porte exact et l'adresse complète en quelques secondes.",
        "product_feat6_title": "Protection silencieuse contre la perte",
        "product_feat6_desc": "Si 1 adresse sur 20 est illisible, le système calcule un itinéraire pour les 19 adresses valides et isole l'erreur sans planter.",
        "product_feat7_title": "Répartiteur en direct",
        "product_feat7_desc": "Locy fournit des mises à jour en direct ('Lecture...', 'Recherche de coordonnées...') comme un répartiteur virtuel en temps réel.",
        "product_cta_title": "Prêt à commencer ?",
        "product_cta_desc": "Aucune carte de crédit requise. Commencez à optimiser dès aujourd'hui."
    }
}

with open("locales/translations.js", "r", encoding="utf-8") as f:
    text = f.read()

for lang, data in new_data.items():
    search_str = f'"{lang}": {{'
    keys_str = ""
    for k, v in data.items():
        keys_str += f'        "{k}": {json.dumps(v)},\n'
    replace_str = f'"{lang}": {{\n' + keys_str
    text = text.replace(search_str, replace_str, 1)

with open("locales/translations.js", "w", encoding="utf-8") as f:
    f.write(text)

print("Patch 2 done!")
