import re
import json

new_data = {
    "es": {
        "pricing_hero_sub": "PRECIOS POR USO",
        "pricing_hero_title": "Pague por <span class=\"text-gradient\">coordenadas</span> válidas.<br>Nada más.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "Para pruebas y pequeños pilotos.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 Consultas / mes",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Motor de IA Multimodal",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Soporte Comunitario",
        "pricing_card1_cta": "Comenzar Gratis",
        "pricing_card2_badge": "MÁS POPULAR",
        "pricing_card2_title": "Estándar",
        "pricing_card2_desc": "Pago por uso.",
        "pricing_card2_price": "$0.05 <span>/ consulta</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Consultas Ilimitadas",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Cola Prioritaria",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Optimización de Rutas incluida",
        "pricing_card2_cta": "Empezar",
        "pricing_card3_title": "Empresarial",
        "pricing_card3_desc": "Para grandes flotas.",
        "pricing_card3_price": "Personalizado",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Descuentos por Volumen",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Gestor de Cuenta",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 99.9% de SLA Garantizado",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Soporte 24/7",
        "pricing_card3_cta": "Contactar Ventas",
        "pricing_faq_title": "Preguntas Frecuentes",
        "pricing_faq1_q": "¿Retienen las imágenes?",
        "pricing_faq1_a": "No. Locy opera con cero retención. Las imágenes se procesan en la memoria volátil y se eliminan después de la extracción de las coordenadas.",
        "pricing_faq2_q": "¿Qué se considera una 'consulta'?",
        "pricing_faq2_a": "Una consulta exitosa de API o un mensaje de WhatsApp que devuelva una coordenada válida. Los errores no se facturan.",
        "pricing_faq3_q": "¿Existe un límite de volumen?",
        "pricing_faq3_a": "El nivel Estándar soporta hasta 10 peticiones por segundo. Para mayor capacidad, contacte a ventas Empresariales para instancias dedicadas.",
        "pricing_faq4_q": "¿Puedo almacenar las coordenadas (caché)?",
        "pricing_faq4_a": "Sí. Una vez que paga por los datos, son suyos. Puede guardar y reutilizar las coordenadas indefinidamente.",
        "product_hero_sub": "PARA CONDUCTORES Y FLOTAS",
        "product_hero_title": "Deje de escribir <span class=\"text-gradient\">direcciones.</span>",
        "product_hero_desc": "La herramienta favorita de los conductores. Simplemente reenvíe a WhatsApp. Verificación en milisegundos.",
        "product_seca_title": "Solo tome una foto. <br>Nosotros hacemos el resto.",
        "product_seca_desc": "Los conductores no deberían ser digitadores. Locy lee incluso la letra más desordenada.<br><br>Nuestra IA detecta automáticamente los puntos de entrega.",
        "product_card_res": "Resultado",
        "product_card_ver": "VERIFICADO 99.9%",
        "product_card_det": "Dirección Detectada",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Coordenadas",
        "product_card_ctx": "Contexto",
        "product_card_ctx_1": "Comercial",
        "product_card_ctx_2": "Entrada",
        "product_secb_title": "Verificación Precisa.",
        "product_secb_desc": "No adivinamos. Verificamos.",
        "product_feat1_title": "Nunca se pierda",
        "product_feat1_desc": "Revisamos direcciones contra cuadrículas geoespaciales. Devolvemos lat/long verificadas.",
        "product_feat2_title": "Secuenciación Dinámica",
        "product_feat2_desc": "Envíe 25 paradas. Reciba 1 ruta óptima. Termine su ruta más rápido.",
        "product_feat3_title": "Respuesta Instantánea",
        "product_feat3_desc": "Del envío de la imagen a la generación de la ruta en menos de un segundo.",
        "product_secc_title": "Funciones Avanzadas.",
        "product_secc_desc": "Diseñado para la vida real en la ruta.",
        "product_feat4_title": "Reversa con un toque",
        "product_feat4_desc": "¿Desea iniciar su ruta en reversa? Toque 'Invertir' en WhatsApp (LIFO).",
        "product_feat5_title": "Pin-a-Texto",
        "product_feat5_desc": "¿Perdido? Envíe su pin GPS actual y reciba la dirección exacta en texto al instante.",
        "product_feat6_title": "Protección contra pérdida",
        "product_feat6_desc": "Si 1 de 20 direcciones es ilegible, enrutamos las 19 correctas y listamos 1 no leída sin fallar.",
        "product_feat7_title": "Despachador en vivo",
        "product_feat7_desc": "Proporcionamos actualizaciones de escritura en vivo ('Leyendo...', 'Buscando...').",
        "product_cta_title": "¿Listo para empezar?",
        "product_cta_desc": "No requiere tarjeta de crédito. Comience a optimizar hoy."
    },
    "et": {
        "pricing_hero_sub": "KASUTUSPÕHINE HIND",
        "pricing_hero_title": "Makske kehtivate <span class=\"text-gradient\">koordinaatide</span> eest.<br>Ei midagi muud.",
        "pricing_card1_title": "Liivakast",
        "pricing_card1_desc": "Testimiseks ja väike-pilootideks.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 päringut / kuus",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Mitmemodulaarne AI mootor",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Kogukonna tugi",
        "pricing_card1_cta": "Alusta tasuta",
        "pricing_card2_badge": "POPULAARSEIM",
        "pricing_card2_title": "Standard",
        "pricing_card2_desc": "Maksa vastavalt kasutusele.",
        "pricing_card2_price": "$0.05 <span>/ päring</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Piiramatud päringud",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Eelisjärjekord",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Marsruudi optimeerimine",
        "pricing_card2_cta": "Alusta",
        "pricing_card3_title": "Ettevõte",
        "pricing_card3_desc": "Suurtele autoparkidele.",
        "pricing_card3_price": "Eritellimus",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Mahusoodustused",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Isiklik kliendihaldur",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 99.9% SLA garantii",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 24/7 Tugi",
        "pricing_card3_cta": "Võta ühendust",
        "pricing_faq_title": "Korduma kippuvad küsimused",
        "pricing_faq1_q": "Kas te säilitate pilte?",
        "pricing_faq1_a": "Ei. Locy ei säilita andmeid. Pildid töödeldakse ajutises mälus ja kustutatakse kohe. Me ei kasuta teie andmeid mudelite treenimiseks.",
        "pricing_faq2_q": "Mis loeb üheks 'päringuks' (Look)?",
        "pricing_faq2_a": "Iga edukas API või WhatsApp sõnum, mis tagastab kehtiva koordinaadi. Vigu ei maksustata.",
        "pricing_faq3_q": "Kas on mahupiirang?",
        "pricing_faq3_a": "Standardpakett toetab kuni 10 päringut sekundis. Suurema mahu jaoks võtke meiega ühendust.",
        "pricing_faq4_q": "Kas ma võin koordinaate salvestada?",
        "pricing_faq4_a": "Jah. Kui olete andmete eest maksnud, võite neid püsivalt säilitada ja uuesti kasutada.",
        "product_hero_sub": "JUHTIDELE JA PARKIIDELE",
        "product_hero_title": "Lõpetage <span class=\"text-gradient\">aadresside</span> trükkimine.",
        "product_hero_desc": "Tööriist, mida juhid armastavad. Saada lihtsalt WhatsAppi. Tuvastus millisekunditega.",
        "product_seca_title": "Tehke lihtsalt pilt. <br>Meie teeme ülejäänu.",
        "product_seca_desc": "Meie AI tuvastab saatelehtedelt aadressid automaatselt. Teie lihtsalt sõidate.",
        "product_card_res": "Analüüsi tulemus",
        "product_card_ver": "KINNITATUD 99.9%",
        "product_card_det": "Tuvastatud aadress",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Koordinaadid",
        "product_card_ctx": "Kontekst",
        "product_card_ctx_1": "Ärihoone",
        "product_card_ctx_2": "Peasissepääs",
        "product_secb_title": "Täpne tuvastamine.",
        "product_secb_desc": "Me ei arva. Me kontrollime.",
        "product_feat1_title": "Ärge kunagi eksige",
        "product_feat1_desc": "Tagastame kontrollitud koordinaadid, et saaksite sõita otse ukseni.",
        "product_feat2_title": "Dünaamiline järjestamine",
        "product_feat2_desc": "Saada 25 peatust. Saa 1 optimaalne marsruut.",
        "product_feat3_title": "Kohene vastus",
        "product_feat3_desc": "Pildi üleslaadimisest marsruudini vähem kui sekundiga.",
        "product_secc_title": "Täiustatud funktsioonid.",
        "product_secc_desc": "Loodud reaalse teeolukorra jaoks.",
        "product_feat4_title": "Ühe puutega tagurpidi marsruut",
        "product_feat4_desc": "Vajutage WhatsAppis 'Pööra ümber' ja optimeering luuakse uuesti lõpust algusesse.",
        "product_feat5_title": "Pin-to-Text",
        "product_feat5_desc": "Jaga oma GPS-i ja saad sekunditega täpse ukse numbri ja teksti.",
        "product_feat6_title": "Kaitse kadude eest",
        "product_feat6_desc": "Kui 1 aadress 20-st on loetamatu, optimeerime 19 head aadressi katkestusteta.",
        "product_feat7_title": "Klienditeenindaja",
        "product_feat7_desc": "Locy pakub WhatsAppis reaalajas värskendusi ('Loen...', 'Otsin...').",
        "product_cta_title": "Valmis alustama?",
        "product_cta_desc": "Krediitkaarti pole vaja. Alusta optimeerimist täna."
    },
    "it": {
        "pricing_hero_sub": "TARIFFE A CONSUMO",
        "pricing_hero_title": "Paga per <span class=\"text-gradient\">coordinate</span> valide.<br>Nient'altro.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "Per test e piccoli progetti pilota.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 Richieste / mese",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Motore AI Multimodale",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Supporto della Community",
        "pricing_card1_cta": "Inizia Gratis",
        "pricing_card2_badge": "PIÙ POPOLARE",
        "pricing_card2_title": "Standard",
        "pricing_card2_desc": "Pay-as-you-go utility.",
        "pricing_card2_price": "$0.05 <span>/ richiesta</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Richieste Illimitate",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Coda Prioritaria",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Ottimizzazione Percorsi inclusa",
        "pricing_card2_cta": "Inizia Ora",
        "pricing_card3_title": "Enterprise",
        "pricing_card3_desc": "Per grandi flotte.",
        "pricing_card3_price": "Personalizzato",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Sconti per Volume",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Account Manager dedicato",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> SLA Garantito al 99.9%",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Supporto 24/7",
        "pricing_card3_cta": "Contatta le Vendite",
        "pricing_faq_title": "Domande Frequenti",
        "pricing_faq1_q": "Conservate le immagini?",
        "pricing_faq1_a": "No. Locy opera con ritenzione zero. Le immagini vengono elaborate in memoria volatile ed eliminate istantaneamente. Non addestriamo i nostri modelli sui tuoi dati.",
        "pricing_faq2_q": "Cosa conta come una 'Richiesta'?",
        "pricing_faq2_a": "Una API o un messaggio WhatsApp che restituisce una coordinata o un percorso valido. Gli errori non vengono fatturati.",
        "pricing_faq3_q": "C'è un limite di volume?",
        "pricing_faq3_a": "Il livello Standard supporta fino a 10 richieste al secondo. Contatta le vendite per istanze dedicate.",
        "pricing_faq4_q": "Posso salvare le coordinate nella cache?",
        "pricing_faq4_a": "Sì. Una volta pagati i dati, sono tuoi. Puoi memorizzare e riutilizzare le coordinate a tempo indeterminato.",
        "product_hero_sub": "PER AUTISTI E FLOTTE",
        "product_hero_title": "Smetti di digitare <span class=\"text-gradient\">indirizzi.</span>",
        "product_hero_desc": "Lo strumento amato dagli autisti. Basta inoltrare a WhatsApp. Verifica in millisecondi.",
        "product_seca_title": "Fai una foto. <br>Pensiamo a tutto noi.",
        "product_seca_desc": "La nostra AI automatizza il rilevamento degli indirizzi dalle etichette. Tu devi solo guidare.",
        "product_card_res": "Risultato",
        "product_card_ver": "VERIFICATO 99.9%",
        "product_card_det": "Indirizzo Rilevato",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Coordinate",
        "product_card_ctx": "Contesto",
        "product_card_ctx_1": "Commerciale",
        "product_card_ctx_2": "Ingresso Principale",
        "product_secb_title": "Verifica Precisa.",
        "product_secb_desc": "Non tiriamo a indovinare. Verifiamo.",
        "product_feat1_title": "Non perderti mai",
        "product_feat1_desc": "Restituiamo coordinate precise per portarti dritto alla porta.",
        "product_feat2_title": "Sequenziamento Dinamico",
        "product_feat2_desc": "Invia 25 fermate. Ricevi 1 percorso ottimale.",
        "product_feat3_title": "Risposta Immediata",
        "product_feat3_desc": "Dal caricamento dell'immagine alla generazione del percorso in meno di un secondo.",
        "product_secc_title": "Funzioni Autista Avanzate.",
        "product_secc_desc": "Progettato per la realtà della strada.",
        "product_feat4_title": "Inversione del percorso in un tap",
        "product_feat4_desc": "Tocca un pulsante per invertire automaticamente l'ordine del percorso.",
        "product_feat5_title": "Pin-to-Text",
        "product_feat5_desc": "Invia il tuo Pin GPS a Locy per ricevere l'indirizzo scritto esatto.",
        "product_feat6_title": "Protezione contro le perdite",
        "product_feat6_desc": "Se un indirizzo è illeggibile, separiamo l'errore e ottimizziamo il resto.",
        "product_feat7_title": "Dispatcher Virtuale in tempo reale",
        "product_feat7_desc": "WhatsApp ti fornisce aggiornamenti mentre elaboriamo il percorso.",
        "product_cta_title": "Pronto per iniziare?",
        "product_cta_desc": "Nessuna carta di credito richiesta. Inizia a ottimizzare oggi."
    }
}

with open("locales/translations.js", "r", encoding="utf-8") as f:
    text = f.read()

for lang, data in new_data.items():
    search_str = f'"{lang}": {{'
    keys_str = ""
    for k, v in data.items():
        keys_str += f'        "{k}": {json.dumps(v)},\n'
    replace_str = f'"{lang}": {{\n' + keys_str
    text = text.replace(search_str, replace_str, 1)

with open("locales/translations.js", "w", encoding="utf-8") as f:
    f.write(text)

print("Patch 3 done!")
