import re
import json

new_data = {
    "en": {
        "pricing_hero_sub": "UTILITY PRICING",
        "pricing_hero_title": "Pay for valid <span class=\"text-gradient\">coordinates.</span><br>Nothing else.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "For testing and small pilots.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 50 Lookups / mo",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Multimodal AI Engine",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Community Support",
        "pricing_card1_cta": "Start Free",
        "pricing_card2_badge": "MOST POPULAR",
        "pricing_card2_title": "Standard",
        "pricing_card2_desc": "Pay-as-you-go utility.",
        "pricing_card2_price": "$0.05 <span>/ look</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Unlimited Lookups",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Priority Queueing",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Route Optimization included",
        "pricing_card2_cta": "Get Started",
        "pricing_card3_title": "Enterprise",
        "pricing_card3_desc": "For high-volume fleets.",
        "pricing_card3_price": "Custom",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Volume Discounts",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Dedicated Manager",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 99.9% SLA Guarantee",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Dedicated Support",
        "pricing_card3_cta": "Contact Sales",
        "pricing_faq_title": "Common Questions",
        "pricing_faq1_q": "Do you retain the images?",
        "pricing_faq1_a": "No. Locy is a zero-retention pipeline. Images are processed in volatile memory and discarded immediately after coordinate extraction. We do not use your data to train our models.",
        "pricing_faq2_q": "What counts as a 'Look'?",
        "pricing_faq2_a": "A 'Look' is any successful service request or WhatsApp message that returns a valid coordinate or route. Errors and ambiguous results are not billed.",
        "pricing_faq3_q": "Is there a volume limit?",
        "pricing_faq3_a": "The Standard tier supports up to 10 requests per second (RPS). For higher throughput, please contact Enterprise sales for dedicated instances.",
        "pricing_faq4_q": "Can I cache the coordinates?",
        "pricing_faq4_a": "Yes. Once you pay for the data, it is yours. You are free to cache, store, and reuse the coordinates indefinitely.",
        "product_hero_sub": "FOR DRIVERS & FLEETS",
        "product_hero_title": "Stop Typing <span class=\"text-gradient\">Addresses.</span>",
        "product_hero_desc": "The tool drivers love. Stop typing addresses manually. Just forward to WhatsApp. Verification in milliseconds.",
        "product_seca_title": "Just Snap a Photo. <br>We Do the Rest.",
        "product_seca_desc": "Drivers shouldn't be data entry clerks. Locy reads even the messiest handwriting.<br><br>Our AI ingests manifests, notes, and labels, automatically detecting delivery points. You just drive.",
        "product_card_res": "Analysis Result",
        "product_card_ver": "VERIFIED 99.9%",
        "product_card_det": "Detected Address",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Coordinates",
        "product_card_ctx": "Context",
        "product_card_ctx_1": "Commercial",
        "product_card_ctx_2": "Main Entrance",
        "product_secb_title": "Pin-Point Verification.",
        "product_secb_desc": "We don't guess. We verify.",
        "product_feat1_title": "Never Get Lost",
        "product_feat1_desc": "Addresses are cross-referenced against geospatial grids. We return verified Latitude/Longitude coordinates so you go straight to the door.",
        "product_feat2_title": "Dynamic Sequencing",
        "product_feat2_desc": "Submit 25 stops. Receive 1 optimal path. Finish your route faster with AI-optimized sequencing.",
        "product_feat3_title": "Instant Response",
        "product_feat3_desc": "Built for speed. From image upload to route generation in under a second. No waiting at the curb.",
        "product_secc_title": "Advanced Driver Features.",
        "product_secc_desc": "Designed for the realities of the road.",
        "product_feat4_title": "One-Tap Route Reversal",
        "product_feat4_desc": "Want to start your route in reverse? Tap a single 'Reverse' button in WhatsApp. The entire optimization is recreated instantly from last to first (LIFO).",
        "product_feat5_title": "Pin-to-Text",
        "product_feat5_desc": "Lost in a rural area? Drop your current GPS pin to Locy. In seconds, receive the exact door number and full text address. An industry first.",
        "product_feat6_title": "Silent Loss Protection",
        "product_feat6_desc": "If 1 out of 20 addresses is completely illegible, the system never crashes. It instantly routes the 19 good addresses and transparently lists the 1 unreadable one, never leaving drivers stranded.",
        "product_feat7_title": "Live Dispatcher UX",
        "product_feat7_desc": "Locy isn't a silent bot. From the moment you send a photo, it provides live typing updates ('Reading...', 'Searching coordinates...'), acting as your real-time virtual dispatcher on the road.",
        "product_cta_title": "Ready to start?",
        "product_cta_desc": "No credit card required. Start optimizing today."
    },
    "tr": {
        "pricing_hero_sub": "KULLANIM BAZLI FİYATLANDIRMA",
        "pricing_hero_title": "Sadece geçerli <span class=\"text-gradient\">koordinatlar</span> için ödeyin.<br>Başka hiçbir şey için değil.",
        "pricing_card1_title": "Sandbox",
        "pricing_card1_desc": "Testler ve küçük pilot uygulamalar için.",
        "pricing_card1_price": "$0",
        "pricing_card1_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Ayda 50 Sorgu",
        "pricing_card1_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Çok Modlu Yapay Zeka (AI)",
        "pricing_card1_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Topluluk Desteği",
        "pricing_card1_cta": "Ücretsiz Başla",
        "pricing_card2_badge": "EN POPÜLER",
        "pricing_card2_title": "Standart",
        "pricing_card2_desc": "Kullandıkça öde modeli.",
        "pricing_card2_price": "$0.05 <span>/ sorgu</span>",
        "pricing_card2_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Sınırsız Sorgu",
        "pricing_card2_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Öncelikli İşlem Sırası",
        "pricing_card2_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Rota Optimizasyonu Dahil",
        "pricing_card2_cta": "Hemen Başla",
        "pricing_card3_title": "Kurumsal",
        "pricing_card3_desc": "Yüksek hacimli filolar için.",
        "pricing_card3_price": "Özel",
        "pricing_card3_feat1": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Hacim İndirimleri",
        "pricing_card3_feat2": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> Özel Müşteri Temsilcisi",
        "pricing_card3_feat3": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> %99.9 SLA Garantisi",
        "pricing_card3_feat4": "<span translate=\"no\" class=\"material-symbols-outlined notranslate\">check</span> 7/24 Destek",
        "pricing_card3_cta": "Satış Ekibiyle Görüşün",
        "pricing_faq_title": "Sıkça Sorulan Sorular",
        "pricing_faq1_q": "Görselleri saklıyor musunuz?",
        "pricing_faq1_a": "Hayır. Locy sıfır-veri-saklama prensibiyle çalışır. Görseller geçici bellekte işlenir ve koordinat çıkarıldıktan sonra anında silinir. Verilerinizi modellerimizi eğitmek için kullanmıyoruz.",
        "pricing_faq2_q": "'Sorgu' (Look) ne anlama geliyor?",
        "pricing_faq2_a": "Bir 'Sorgu', geçerli bir koordinat veya rota döndüren herhangi bir başarılı API isteği veya WhatsApp mesajıdır. Hatalı ve eksik sonuçlar faturalandırılmaz.",
        "pricing_faq3_q": "Hacim sınırı var mı?",
        "pricing_faq3_a": "Standart paket saniyede 10 isteğe (RPS) kadar destekler. Daha yüksek kapasite için özel sunucular ayarlamak üzere Kurumsal satış ekibiyle iletişime geçin.",
        "pricing_faq4_q": "Koordinatları önbelleğe alabilir miyim (cache)?",
        "pricing_faq4_a": "Evet. Veriyi satın aldıktan sonra tamamen size aittir. Koordinatları süresiz olarak saklayabilir ve yeniden kullanabilirsiniz.",
        "product_hero_sub": "SÜRÜCÜLER VE FİLOLAR İÇİN",
        "product_hero_title": "Adres Yazmayı <span class=\"text-gradient\">Bırakın.</span>",
        "product_hero_desc": "Sürücülerin sevdiği araç. Adresleri manuel olarak girmeyi bırakın. Sadece WhatsApp'a iletin. Milisaniyeler içinde doğrulayın.",
        "product_seca_title": "Sadece Bir Fotoğraf Çekin. <br>Gerisini Biz Hallederiz.",
        "product_seca_desc": "Sürücüler veri giriş memuru olmamalı. Locy en karmaşık el yazılarını bile okur.<br><br>Yapay zekamız kargo etiketlerini ve teslimat notlarını okur, adresi anında tespit eder. Siz sadece sürün.",
        "product_card_res": "Analiz Sonucu",
        "product_card_ver": "DOĞRULANDI %99.9",
        "product_card_det": "Tespit Edilen Adres",
        "product_card_addr": "Narva mnt 5, Tallinn 10117",
        "product_card_coord": "Koordinatlar",
        "product_card_ctx": "Bağlam",
        "product_card_ctx_1": "Ticari",
        "product_card_ctx_2": "Ana Giriş",
        "product_secb_title": "Nokta Atışı Doğrulama.",
        "product_secb_desc": "Tahmin etmiyoruz. Doğruluyoruz.",
        "product_feat1_title": "Asla Kaybolmayın",
        "product_feat1_desc": "Adresler coğrafi veritabanlarıyla çapraz referanslanır. Doğrulanmış Enlem/Boylam koordinatları sunuyoruz, böylece doğrudan kapıya gidersiniz.",
        "product_feat2_title": "Dinamik Sıralama",
        "product_feat2_desc": "25 durak gönderin. Tek 1 optimum rota alın. Yapay zeka destekli rota optimizasyonuyla rotanızı daha hızlı bitirin.",
        "product_feat3_title": "Anında Yanıt",
        "product_feat3_desc": "Hız için tasarlandı. Görsel yüklemesinden rotanın oluşturulmasına kadar olan süreç bir saniyenin altındadır.",
        "product_secc_title": "Gelişmiş Sürücü Özellikleri.",
        "product_secc_desc": "Yolun gerçekleri için tasarlandı.",
        "product_feat4_title": "Tek Dokunuşla Geriye Dönük Rota",
        "product_feat4_desc": "Rotanıza sondan mı başlamak istiyorsunuz? WhatsApp'ta 'Rotayı Ters Çevir' düğmesine dokunun. Rota anında en sondan en başa (LIFO) doğru yeniden oluşturulur.",
        "product_feat5_title": "Konumdan Açık Adrese (Pin-to-Text)",
        "product_feat5_desc": "Kırsal alanda kayıp mı oldunuz? GPS konumunuzu Locy'e gönderin. Saniyeler içinde tam kapı numarasını ve açık metin adresini alın. Sektörde bir ilk.",
        "product_feat6_title": "Sessiz Hata Koruması",
        "product_feat6_desc": "20 adresten 1 tanesi tamamen okunaksızsa sistem asla çökmez. Sorunsuz olan 19 adresi anında rotaya dahil eder ve 1 adet okunamayan adresi şeffaf şekilde size bildirir.",
        "product_feat7_title": "Sanal Canlı Dispeçer",
        "product_feat7_desc": "Locy sessiz bir bot değildir. Bir fotoğraf gönderdiğiniz andan itibaren ekranda canlı durum güncellemeleri verir ('Okunuyor...', 'Koordinatlar aranıyor...'), yolda gerçek zamanlı sanal dispeçeriniz gibi davranır.",
        "product_cta_title": "Başlamaya Hazır mısınız?",
        "product_cta_desc": "Kredi kartı gerekmez. Bugünden optimize etmeye başlayın."
    }
}

with open("locales/translations.js", "r", encoding="utf-8") as f:
    text = f.read()

for lang, data in new_data.items():
    search_str = f'"{lang}": {{'
    keys_str = ""
    for k, v in data.items():
        keys_str += f'        "{k}": {json.dumps(v)},\n'
    replace_str = f'"{lang}": {{\n' + keys_str
    text = text.replace(search_str, replace_str, 1)

with open("locales/translations.js", "w", encoding="utf-8") as f:
    f.write(text)

print("Patch 1 done!")
