import json

new_data = {
    "en": {
        "comp_hero_sub": "OUR MISSION",
        "comp_hero_title": "Built for the <span class=\"text-gradient\">Last Mile.</span>",
        "comp_manifesto": "Logistics has a data problem. Drivers are typing addresses. Dispatchers are guessing locations. <br><br>We built Locy to bridge the physical gap with digital precision. We are not an app company. We are an infrastructure company.",
        "comp_val1_title": "Invisible",
        "comp_val1_desc": "The best tool is the one you don't see. We don't ask drivers to install apps. We live where they already are: WhatsApp.",
        "comp_val2_title": "Instant",
        "comp_val2_desc": "Seconds save hours. Our latency is measured in milliseconds because a driver standing on a curb can't wait.",
        "comp_val3_title": "Secure",
        "comp_val3_desc": "Zero Retention. Data is processed, converted to coordinates, and immediately flushed from memory. We do not train on customer data.",
        "comp_heri_title": "Born in e-Estonia.",
        "comp_heri_desc1": "Locy is operated by <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> (Reg: 17131887), headquartered in Narva mnt 5, Tallinn.",
        "comp_heri_desc2": "Built within the frameworks of the world's most advanced digital society. EU-compliant. GDPR-native. Secure by design.",
        "eco_hero_sub": "FOR E-COMMERCE",
        "eco_hero_title": "First time right. <br><span class=\"text-gradient-cyan\">Zero returns.</span>",
        "eco_hero_desc": "\"Address Not Found\" is a profit killer. Locy verifies the location before the truck leaves the depot.",
        "eco_hero_cta": "Test Verification",
        "eco_feat1_title": "Reduce Returns",
        "eco_feat1_desc": "Failed deliveries cost 3x shipping. Fix the address at the source.",
        "eco_feat2_title": "Barcode Ready",
        "eco_feat2_desc": "Drivers scan the shipping label. Locy parses the barcode and verifies the geotag instantly.",
        "eco_feat3_title": "Proof of Presence",
        "eco_feat3_desc": "Ensure the courier was actually at the door with GPS-stamped verification.",
        "eco_steps_title": "The Flow",
        "eco_step1_title": "Scan Label",
        "eco_step1_desc": "Driver scans barcode with camera.",
        "eco_step2_title": "Check Address",
        "eco_step2_desc": "Deliverability verified instantly.",
        "eco_step3_title": "Deliver",
        "eco_step3_desc": "Navigate to verified entrance.",
        "eco_explore_title": "EXPLORE OTHER SOLUTIONS",
        "eco_explore_rest_title": "Restaurants",
        "eco_explore_rest_desc": "Hot food, cold logic.",
        "eco_explore_emerg_title": "Emergency",
        "eco_explore_emerg_desc": "Precision life-saving.",
        "eco_cta_title": "Ready to speed up deliveries?",
        "eco_cta_desc": "Save 30 seconds per delivery. No credit card required.",
        "em_hero_sub": "EMERGENCY RESPONSE",
        "em_hero_title": "When seconds <br><span class=\"text-gradient-alert\">count.</span>",
        "em_hero_desc": "GPS says \"You have arrived\". But the entrance is 200m away around the block. Locy guides you to the exact door.",
        "em_hero_cta": "Deploy Pilot",
        "em_feat1_title": "Exact Entrance",
        "em_feat1_desc": "Map pins drop in the center of the building. We drop them at the active door.",
        "em_feat2_title": "Dispatcher Link",
        "em_feat2_desc": "Dispatchers can send a \"Locy Link\" to the caller to instantly verify their location via WhatsApp.",
        "em_feat3_title": "Offline First",
        "em_feat3_desc": "Works on low-bandwidth networks where data-heavy map apps fail.",
        "em_steps_title": "Response Protocol",
        "em_step1_title": "Send Link",
        "em_step1_desc": "Dispatcher sends Locy Link.",
        "em_step2_title": "One Click",
        "em_step2_desc": "Caller taps. GPS captured.",
        "em_step3_title": "Found",
        "em_step3_desc": "Route to practical entrance.",
        "rest_hero_sub": "FOR RESTAURANTS",
        "rest_hero_title": "Hot food. <br><span class=\"text-gradient-red\">Cold logic.</span>",
        "rest_hero_desc": "Your margin dies when the driver calls the customer to ask \"Which building?\". Locy pins the exact door. Zero friction.",
        "rest_hero_cta": "Start Delivery Demo",
        "rest_feat1_title": "Kill Waiting Time",
        "rest_feat1_desc": "Drivers don't type addresses. They snap the receipt. We route them instantly.",
        "rest_feat2_title": "Apartment Accuracy",
        "rest_feat2_desc": "We detect access codes and entrance locations from context data. No more gate-waiting.",
        "rest_feat3_title": "Made for Moto",
        "rest_feat3_desc": "Interface designed for gloved hands and high-glare environments. Big buttons, zero fluff.",
        "rest_steps_title": "How it works",
        "rest_step1_title": "Snap Receipt",
        "rest_step1_desc": "Driver sends photo to WhatsApp.",
        "rest_step2_title": "Locy Scans",
        "rest_step2_desc": "Text parsed. Coordinate resolved.",
        "rest_step3_title": "Pin Drop",
        "rest_step3_desc": "Exact building entrance received."
    },
    "tr": {
        "comp_hero_sub": "MİSYONUMUZ",
        "comp_hero_title": "<span class=\"text-gradient\">Son Kilometre</span> için Tasarlandı.",
        "comp_manifesto": "Lojistikte bir veri problemi var. Sürücüler adresleri elle yazıyor. Dispeçerler konum tahmin ediyor. <br><br>Fiziksel dünyadaki bu boşluğu dijital hassasiyetle kapatmak için Locy'i geliştirdik. Biz bir uygulama değil, altyapı şirketiyiz.",
        "comp_val1_title": "Görünmez",
        "comp_val1_desc": "En iyi araç görmediğiniz araçtır. Sürücülerden uygulama yüklemelerini istemiyoruz. Zaten bulundukları yerde yaşıyoruz: WhatsApp.",
        "comp_val2_title": "Anında",
        "comp_val2_desc": "Saniyeler saatleri kurtarır. Gecikme süremiz milisaniyelerle ölçülür çünkü motor üzerinde bekleyen biri hızlı olmak zorundadır.",
        "comp_val3_title": "Güvenli",
        "comp_val3_desc": "Sıfır Veri Saklama. Veriler işlenir, koordinata dönüştürülür ve hafızadan tamamen silinir. Modellerimizi müşteri verisiyle eğitmiyoruz.",
        "comp_heri_title": "e-Estonya'da doğdu.",
        "comp_heri_desc1": "Locy, Tallinn merkezli <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> (Kayıt: 17131887) tarafından geliştirilmekte ve yönetilmektedir.",
        "comp_heri_desc2": "Dünyanın en gelişmiş dijital toplumunun altyapısında kurulmuştur. Avrupa Birliği ve GDPR uyumludur.",
        "eco_hero_sub": "E-TİCARET İÇİN",
        "eco_hero_title": "İlk seferde doğru. <br><span class=\"text-gradient-cyan\">Sıfır iade.</span>",
        "eco_hero_desc": "\"Adres Bulunamadı\" iadeleri kârı bitirir. Locy, kargo aracı depodan çıkmadan adresi doğrular.",
        "eco_hero_cta": "Doğrulamayı Test Et",
        "eco_feat1_title": "İadeleri Azaltın",
        "eco_feat1_desc": "Başarısız teslimatlar 3 kat kargo maliyeti yaratır. Adresi kaynağında doğrulayın.",
        "eco_feat2_title": "Barkod Uyumlu",
        "eco_feat2_desc": "Sürücüler kargo etiketini tarar. Locy barkodu çözer ve konumu saniyeler içinde tespit eder.",
        "eco_feat3_title": "Gps ile Kanıt",
        "eco_feat3_desc": "Kuryenin gerçekten kapıda olduğundan emin olmak için GPS damgalı doğrulama sağlayın.",
        "eco_steps_title": "Akış",
        "eco_step1_title": "Etiketi Tara",
        "eco_step1_desc": "Sürücü barkodu veya adresi çeker.",
        "eco_step2_title": "Adresi Kontrol Et",
        "eco_step2_desc": "Teslim edilebilirlik anında onaylanır.",
        "eco_step3_title": "Teslim Et",
        "eco_step3_desc": "Doğrulanmış kapıya yönlendirilir.",
        "eco_explore_title": "DİĞER ÇÖZÜMLERİ KEŞFEDİN",
        "eco_explore_rest_title": "Restoranlar",
        "eco_explore_rest_desc": "Sıcak yemek, soğuk mantık.",
        "eco_explore_emerg_title": "Acil Durum",
        "eco_explore_emerg_desc": "Hayat kurtaran hassasiyet.",
        "eco_cta_title": "Teslimatları hızlandırmaya hazır mısınız?",
        "eco_cta_desc": "Her teslimatta ortalama 30 saniye kazanın. Kredi kartı gerekmez.",
        "em_hero_sub": "ACİL DURUM MÜDAHALESİ",
        "em_hero_title": "Saniyeler <br><span class=\"text-gradient-alert\">ödül olduğunda.</span>",
        "em_hero_desc": "Navigasyon \"Geldiniz\" diyor ama giriş diğer sokakta... Locy acil durum ekiplerini tam doğru kapıya yönlendirir.",
        "em_hero_cta": "Pilot Uygulama Başlat",
        "em_feat1_title": "Kesin Giriş Kapısı",
        "em_feat1_desc": "Haritalar pini binanın ortasına bırakır. Biz pini doğrudan bina giriş kapısına yerleştiririz.",
        "em_feat2_title": "Dispeçer Linki",
        "em_feat2_desc": "WhatsApp üzerinden gönderilen bir 'Locy Linki' ile, yardım çağıran kişinin konumu anında belirlenir.",
        "em_feat3_title": "Düşük İnternette Çalışır",
        "em_feat3_desc": "Ağır harita uygulamalarının çöktüğü düşük bant genişliği olan bölgelerde tıkır tıkır çalışır.",
        "em_steps_title": "Müdahale Protokolü",
        "em_step1_title": "Linki Gönder",
        "em_step1_desc": "Görevli Locy Linkini iletir.",
        "em_step2_title": "Tek Tık",
        "em_step2_desc": "Arayan tıklar, GPS alınır.",
        "em_step3_title": "Bulundu!",
        "em_step3_desc": "Pratik girişe anında rota.",
        "rest_hero_sub": "RESTORANLAR İÇİN",
        "rest_hero_title": "Sıcak yemek. <br><span class=\"text-gradient-red\">Soğuk mantık.</span>",
        "rest_hero_desc": "Kurye müşteriyi \"Hangi apartmandı?\" diye aradığında kâr marjınız ölür. Locy doğru kapıyı bulur.",
        "rest_hero_cta": "Teslimat Demosunu Başlat",
        "rest_feat1_title": "Bekleme Süresini Kısalt",
        "rest_feat1_desc": "Kuryeler adres yazmaz, adisyonun fotoğrafını çeker ve anında rota oluşturur.",
        "rest_feat2_title": "Bina Hassasiyeti",
        "rest_feat2_desc": "Sipariş notlarından bina şifresini ve doğru kapıyı anlar. Kapıda beklemeye son.",
        "rest_feat3_title": "Motorlar İçin Yapıldı",
        "rest_feat3_desc": "Eldivenli eller ve parlayan güneş altındaki ekranlar için büyük butonlarla donatıldı.",
        "rest_steps_title": "Nasıl Çalışır?",
        "rest_step1_title": "Adisyonu Çek",
        "rest_step1_desc": "Kurye fişi WhatsApp'a atar.",
        "rest_step2_title": "Locy Tarar",
        "rest_step2_desc": "Yazı çözümlenir, koordinat bulunur.",
        "rest_step3_title": "Gerçek Rota",
        "rest_step3_desc": "Kesin bina girişine yönlendirilir."
    },
    "de": {
        "comp_hero_sub": "UNSERE MISSION",
        "comp_hero_title": "Gebaut für die <span class=\"text-gradient\">Letzte Meile.</span>",
        "comp_manifesto": "Logistik hat ein Datenproblem. Fahrer tippen Adressen. Disponenten raten Standorte. Wir haben Locy entwickelt, um diese physische Lücke mit digitaler Präzision zu schließen. Wir sind kein App-Unternehmen. Wir sind ein Infrastruktur-Unternehmen.",
        "comp_val1_title": "Unsichtbar",
        "comp_val1_desc": "Wir bitten Fahrer nicht, Apps zu installieren. Wir leben dort, wo sie bereits sind: WhatsApp.",
        "comp_val2_title": "Sofortig",
        "comp_val2_desc": "Sekunden sparen Stunden. Unsere Latenz wird in Millisekunden gemessen, denn ein wartender Fahrer hat keine Zeit.",
        "comp_val3_title": "Sicher",
        "comp_val3_desc": "Zero Retention. Daten werden zu Koordinaten verarbeitet und sofort aus dem Speicher gelöscht.",
        "comp_heri_title": "Geboren in e-Estonia.",
        "comp_heri_desc1": "Locy wird von <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> (Reg: 17131887) mit Sitz in Tallinn betrieben.",
        "comp_heri_desc2": "EU-konform. GDPR-nativ. Secure by design.",
        "eco_hero_sub": "FÜR E-COMMERCE",
        "eco_hero_title": "Gleich beim ersten Mal. <br><span class=\"text-gradient-cyan\">Null Retouren.</span>",
        "eco_hero_desc": "'Adresse nicht gefunden' zerstört Ihre Marge. Locy verifiziert Standorte, bevor der LKW das Depot verlässt.",
        "eco_hero_cta": "Verifizierung testen",
        "eco_feat1_title": "Retouren reduzieren",
        "eco_feat1_desc": "Fehlgeschlagene Lieferungen kosten 3x so viel. Reparieren Sie die Adresse an der Quelle.",
        "eco_feat2_title": "Barcode Ready",
        "eco_feat2_desc": "Fahrer scannen das Etikett. Locy liest den Barcode und verifiziert das Geotag.",
        "eco_feat3_title": "Anwesenheitsnachweis",
        "eco_feat3_desc": "Stellen Sie sicher, dass der Kurier dank GPS-Validierung tatsächlich vor Ort war.",
        "eco_steps_title": "Der Ablauf",
        "eco_step1_title": "Etikett Scannen",
        "eco_step1_desc": "Fahrer scannt den Code.",
        "eco_step2_title": "Adresse Prüfen",
        "eco_step2_desc": "Lieferbarkeit sofort verifiziert.",
        "eco_step3_title": "Zustellen",
        "eco_step3_desc": "Zentimetergenaue Ankunft.",
        "eco_explore_title": "ANDERE LÖSUNGEN",
        "eco_explore_rest_title": "Restaurants",
        "eco_explore_rest_desc": "Heißes Essen, kalte Logik.",
        "eco_explore_emerg_title": "Notdienste",
        "eco_explore_emerg_desc": "Lebensrettende Präzision.",
        "eco_cta_title": "Bereit für schnellere Lieferungen?",
        "eco_cta_desc": "Keine Kreditkarte erforderlich. Sparen Sie 30 Sekunden pro Lieferung.",
        "em_hero_sub": "NOTFALLHILFE",
        "em_hero_title": "Wenn jede <br><span class=\"text-gradient-alert\">Sekunde zählt.</span>",
        "em_hero_desc": "Das Navi sagt 'Sie haben Ihr Ziel erreicht', aber der Eingang ist 200m entfernt. Locy führt Sie genau dorthin.",
        "em_hero_cta": "Pilot starten",
        "em_feat1_title": "Exakter Eingang",
        "em_feat1_desc": "Karten platzieren Stecknadeln in der Mitte des Gebäudes. Wir an der aktiven Tür.",
        "em_feat2_title": "Disponenten-Link",
        "em_feat2_desc": "Ein Klick auf den WhatsApp Locy-Link verifiziert sofort den genauen Standort des Anrufers.",
        "em_feat3_title": "Offline fähig",
        "em_feat3_desc": "Funktioniert auch bei schlechten Netzwerken, wenn schwere Karten-Apps versagen.",
        "em_steps_title": "Einsatzprotokoll",
        "em_step1_title": "Link senden",
        "em_step1_desc": "Disponent schickt Link.",
        "em_step2_title": "Ein Klick",
        "em_step2_desc": "GPS-Daten übermittelt.",
        "em_step3_title": "Gefunden",
        "em_step3_desc": "Route zur Tür.",
        "rest_hero_sub": "FÜR RESTAURANTS",
        "rest_hero_title": "Heißes Essen. <br><span class=\"text-gradient-red\">Kalte Logik.</span>",
        "rest_hero_desc": "Wenn der Fahrer anruft, weil er das Haus nicht findet, schmilzt Ihr Profit. Locy dirigiert sie an die korrekte Tür.",
        "rest_hero_cta": "Liefer-Demo starten",
        "rest_feat1_title": "Wartezeit beenden",
        "rest_feat1_desc": "Kuriere tippen keine Adressen. Foto vom Bon reicht für die sofortige Route.",
        "rest_feat2_title": "Appartment Präzision",
        "rest_feat2_desc": "Wir extrahieren Zugangs-Codes und Notizen. Kein Warten am Tor mehr.",
        "rest_feat3_title": "Für Mopeds gemacht",
        "rest_feat3_desc": "Entwickelt für Handschuhe und Blendlicht. Große Buttons.",
        "rest_steps_title": "Wie es funktioniert",
        "rest_step1_title": "Bon Scannen",
        "rest_step1_desc": "WhatsApp Foto senden.",
        "rest_step2_title": "Locy Liest",
        "rest_step2_desc": "Text verstanden, Koordinaten gelöst.",
        "rest_step3_title": "Route",
        "rest_step3_desc": "Navigation zum Eingang."
    },
    "fr": {
        "comp_hero_sub": "NOTRE MISSION",
        "comp_hero_title": "Conçu pour le <span class=\"text-gradient\">Dernier Kilomètre.</span>",
        "comp_manifesto": "La logistique souffre d'un problème de données. Les livreurs tapent des adresses manuellement. Les répartiteurs devinent les emplacements. Nous avons conçu Locy pour combler cet écart avec une précision numérique.",
        "comp_val1_title": "Invisible",
        "comp_val1_desc": "Pas d'application à installer. Nous existons là où se trouvent déjà les chauffeurs : WhatsApp.",
        "comp_val2_title": "Instantané",
        "comp_val2_desc": "Une latence mesurée en millisecondes pour des décisions en temps réel.",
        "comp_val3_title": "Sécurisé",
        "comp_val3_desc": "Strictement aucune conservation (Zero Retention). Les données sont immédiatement purgées.",
        "comp_heri_title": "Né en e-Estonie.",
        "comp_heri_desc1": "Opéré par <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> (17131887), Tallinn.",
        "comp_heri_desc2": "Conforme à la norme RGPD de l'UE.",
        "eco_hero_sub": "POUR LE E-COMMERCE",
        "eco_hero_title": "Livré du premier coup. <br><span class=\"text-gradient-cyan\">Zéro retour.</span>",
        "eco_hero_desc": "L'erreur d'adresse tue votre rentabilité. Locy vérifie l'adresse avant même le départ du camion.",
        "eco_hero_cta": "Tester la Vérification",
        "eco_feat1_title": "Réduction des retours",
        "eco_feat1_desc": "Évitez de payer trois fois la livraison avec des adresses sûres.",
        "eco_feat2_title": "Compatible Codes-barres",
        "eco_feat2_desc": "Le scan de l'étiquette suffit pour vérifier la destination instantanément.",
        "eco_feat3_title": "Preuve de présence",
        "eco_feat3_desc": "Assurez-vous que le coursier était devant la porte grâce au GPS.",
        "eco_steps_title": "Le Flux",
        "eco_step1_title": "Scanner l'étiquette",
        "eco_step1_desc": "Le chauffeur scanne via l'appareil photo.",
        "eco_step2_title": "Vérifier",
        "eco_step2_desc": "Coordonnées validées.",
        "eco_step3_title": "Livrer",
        "eco_step3_desc": "Itinéraire exact vers la porte.",
        "eco_explore_title": "DÉCOUVREZ NOS SOLUTIONS",
        "eco_explore_rest_title": "Restaurants",
        "eco_explore_rest_desc": "Repas chauds. Logique froide.",
        "eco_explore_emerg_title": "Urgence",
        "eco_explore_emerg_desc": "Des vies sauvées avec précision.",
        "eco_cta_title": "Prêt à accélérer vos livraisons ?",
        "eco_cta_desc": "Gagnez 30 secondes par livraison, sans carte de crédit.",
        "em_hero_sub": "INTERVENTION D'URGENCE",
        "em_hero_title": "Quand chaque seconde <br><span class=\"text-gradient-alert\">compte.</span>",
        "em_hero_desc": "Le GPS vous dépose souvent à 200m du bon bloc. Locy vous guide à l'entrée exacte.",
        "em_hero_cta": "Lancer le Pilote",
        "em_feat1_title": "L'entrée Exacte",
        "em_feat1_desc": "Nous plaçons l'épingle directement sur l'entrée active, pas au milieu du bâtiment.",
        "em_feat2_title": "Lien Répartiteur",
        "em_feat2_desc": "Envoyez un lien WhatsApp pour vérifier instantanément où se trouve l'appelant.",
        "em_feat3_title": "Mode Hors Ligne",
        "em_feat3_desc": "Soutient les réseaux avec une faible bande passante.",
        "em_steps_title": "Protocole de Réponse",
        "em_step1_title": "Lien envoyé",
        "em_step1_desc": "Le répartiteur transfère l'URL.",
        "em_step2_title": "Un Clic",
        "em_step2_desc": "Position GPS capturée.",
        "em_step3_title": "Trouvé",
        "em_step3_desc": "Guidage assuré.",
        "rest_hero_sub": "POUR LES RESTAURANTS",
        "rest_hero_title": "Repas chauds. <br><span class=\"text-gradient-red\">Logique froide.</span>",
        "rest_hero_desc": "Si le livreur demande à votre client \"Quel bâtiment ?\", vous perdez votre marge. Locy résout cela.",
        "rest_hero_cta": "Démarrer la démo",
        "rest_feat1_title": "Fin des attentes",
        "rest_feat1_desc": "Une photo du reçu de caisse, et l'itinéraire d'adresse est prêt.",
        "rest_feat2_title": "Précision d'Appartement",
        "rest_feat2_desc": "Détection automatique des codes portes et accès d'immeuble.",
        "rest_feat3_title": "Conçu pour les Motos",
        "rest_feat3_desc": "Des boutons larges conçus pour les gants.",
        "rest_steps_title": "Comment ça marche",
        "rest_step1_title": "Prendre en Photo",
        "rest_step1_desc": "Photo envoyée sur WhatsApp.",
        "rest_step2_title": "Locy Scan",
        "rest_step2_desc": "Texte et coordonnées décodés.",
        "rest_step3_title": "Validation GPS",
        "rest_step3_desc": "Destination finalisée."
    },
    "es": {
        "comp_hero_sub": "NUESTRA MISIÓN",
        "comp_hero_title": "Construido para la <span class=\"text-gradient\">Última Milla.</span>",
        "comp_manifesto": "La logística tiene un problema de datos. Los conductores escriben direcciones y los despachadores adivinan. Construimos Locy como infraestructura precisa. No somos una app móvil.",
        "comp_val1_title": "Invisible",
        "comp_val1_desc": "No pedimos que instalen apps. Vivimos donde ya operan los usuarios: WhatsApp.",
        "comp_val2_title": "Instantáneo",
        "comp_val2_desc": "Las respuestas tardan milisegundos porque el transportista no tiene tiempo para esperar.",
        "comp_val3_title": "Seguro",
        "comp_val3_desc": "Cero Retención de Datos. No entrenamos con datos del usuario.",
        "comp_heri_title": "Nacido en e-Estonia.",
        "comp_heri_desc1": "Operado por <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> en Estonia.",
        "comp_heri_desc2": "Conforme al RGPD europeo y construido con un diseño sumamente cifrado y seguro.",
        "eco_hero_sub": "PARA E-COMMERCE",
        "eco_hero_title": "Entrega perfecta a la primera. <br><span class=\"text-gradient-cyan\">Cero devoluciones.</span>",
        "eco_hero_desc": "La 'Dirección no encontrada' destruye ganancias. Verificamos todo en tiempo real antes de salir.",
        "eco_hero_cta": "Probar Verificación",
        "eco_feat1_title": "Reduce las Devoluciones",
        "eco_feat1_desc": "Entrega exitosa resolviendo confusiones de ubicación.",
        "eco_feat2_title": "Decodificador de Código de Barras",
        "eco_feat2_desc": "Escanee la etiqueta y confirme la dirección con WhatsApp.",
        "eco_feat3_title": "Prueba de Presencia",
        "eco_feat3_desc": "Use estampas de validación GPS real.",
        "eco_steps_title": "El Proceso",
        "eco_step1_title": "Escanear Etiqueta",
        "eco_step1_desc": "Foto tomada usando cámara.",
        "eco_step2_title": "Verificar",
        "eco_step2_desc": "Localidad analizada al instante.",
        "eco_step3_title": "Entregar",
        "eco_step3_desc": "Llegue a la entrada.",
        "eco_explore_title": "VEA OTRAS SOLUCIONES",
        "eco_explore_rest_title": "Restaurantes",
        "eco_explore_rest_desc": "Comida rápida, entrega precisa.",
        "eco_explore_emerg_title": "Emergencias",
        "eco_explore_emerg_desc": "Salvamento de vidas exacto.",
        "eco_cta_title": "¿Listo para acelerar operaciones?",
        "eco_cta_desc": "Pruebe gratis ahora mismo.",
        "em_hero_sub": "SERVICIOS MÉDICOS O POLICÍAS",
        "em_hero_title": "Cuando cada <br><span class=\"text-gradient-alert\">segundo cuenta.</span>",
        "em_hero_desc": "El GPS ordinario a veces arroja coordenadas distantes de la puerta a 200m. Locy acierta justo allí.",
        "em_hero_cta": "Comenzar Pilotaje",
        "em_feat1_title": "Entrada Directa",
        "em_feat1_desc": "Mapeo inteligente en las puertas principales, no en el centro del edificio.",
        "em_feat2_title": "Ubicación mediante Enlace",
        "em_feat2_desc": "Basta mandar el enlace Locy vía sms o app para validar su geocalización en peligro.",
        "em_feat3_title": "Bajo ancho de banda",
        "em_feat3_desc": "Perfecto para redes de bajo consumo limitadas que no abren mapas grandes.",
        "em_steps_title": "El Protocolo",
        "em_step1_title": "Envía Link",
        "em_step1_desc": "URL de Locy.",
        "em_step2_title": "Toque Único",
        "em_step2_desc": "Aprovechar GPS.",
        "em_step3_title": "Hallado",
        "em_step3_desc": "Ruta hacia el destino.",
        "rest_hero_sub": "PARA RESTAURANTES",
        "rest_hero_title": "Comida caliente. <br><span class=\"text-gradient-red\">Logística veloz.</span>",
        "rest_hero_desc": "Olvídese del repartidor perdido llamando por edificio u apartamento.",
        "rest_hero_cta": "Ver Demostración",
        "rest_feat1_title": "Minimizar Esperas",
        "rest_feat1_desc": "Solo foto del ticket. Ruta instantánea generada vía API.",
        "rest_feat2_title": "Código Apartamento",
        "rest_feat2_desc": "Identifica de notas o ticket los accesos pin de portal y piso interior.",
        "rest_feat3_title": "Hecho para Moto",
        "rest_feat3_desc": "Interface enfocada para el uso en manillas de acelerador con guantes.",
        "rest_steps_title": "El Sistema",
        "rest_step1_title": "Fotografíe Ticket",
        "rest_step1_desc": "Comparte por Whatsapp.",
        "rest_step2_title": "I.A. Evalúa",
        "rest_step2_desc": "Resolviendo exactitud.",
        "rest_step3_title": "Ruta de Entrega",
        "rest_step3_desc": "Camino hasta la misma entrada de puerta."
    },
    "et": {
        "comp_hero_sub": "MEIE MISSIOON",
        "comp_hero_title": "Loodud kohaletoimetamise <span class=\"text-gradient\">viimasele miilile.</span>",
        "comp_manifesto": "Logistikal on andmeprobleem. Locy pole äpp, vaid taustasüsteemi infrastruktuur, mis kaotab aadressiotsingu digitaalse täpsusega.",
        "comp_val1_title": "Nähtamatu",
        "comp_val1_desc": "Pole vaja installida ühtki äppi. Elame WhatsAppis, kus juhid juba niikuinii on.",
        "comp_val2_title": "Kohene",
        "comp_val2_desc": "Mõõdame vastuseid millisekundites, pakkudes juhtidele ülikiiret tuge.",
        "comp_val3_title": "Turvaline",
        "comp_val3_desc": "Andmeid ei säilitata. Kujutised kaovad mälust koheselt pärast analüüsi.",
        "comp_heri_title": "Loodud e-Eestis.",
        "comp_heri_desc1": "Halda <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a>, asukoht Tallinn.",
        "comp_heri_desc2": "Vastab kõikidele Euroopa Liidu andmekaitsestandarditele.",
        "eco_hero_sub": "E-KAUBANDUS",
        "eco_hero_title": "Esimesel korral õige. <br><span class=\"text-gradient-cyan\">Null tagastust.</span>",
        "eco_hero_desc": "Me tuvastame aadressivead enne logistikapargist lahkumist.",
        "eco_hero_cta": "Testi nüüd",
        "eco_feat1_title": "Vähem kulukaid tagastusi",
        "eco_feat1_desc": "Lahendage aadress varakult.",
        "eco_feat2_title": "Ribakood võltsimiskindel",
        "eco_feat2_desc": "Lugege pildilt triipkood ja asukoht minutitega.",
        "eco_feat3_title": "Kliendi asukoha tõendid",
        "eco_feat3_desc": "Kuller võtab GPS pitseriga tõestuse iga kord kaasa.",
        "eco_steps_title": "Kasutvoog",
        "eco_step1_title": "1. Skaneeri silt",
        "eco_step1_desc": "Lihtsalt saada pilt.",
        "eco_step2_title": "2. Analüüs",
        "eco_step2_desc": "Teeme koordinaadi puhtaks.",
        "eco_step3_title": "3. Sõida",
        "eco_step3_desc": "Sõida ukseni.",
        "eco_explore_title": "UURI KA",
        "eco_explore_rest_title": "Restoranilogistika",
        "eco_explore_rest_desc": "Kuum toit, täpne uks.",
        "eco_explore_emerg_title": "Pääste teenused",
        "eco_explore_emerg_desc": "Iga sekund loeb.",
        "eco_cta_title": "Alusta logistika parandamist",
        "eco_cta_desc": "Meilt saab alustada krediitkaardita.",
        "em_hero_sub": "PÄÄSTEOPERATSIOONID",
        "em_hero_title": "Kui loevad  <br><span class=\"text-gradient-alert\">sekundid.</span>",
        "em_hero_desc": "Navigatsiooniseade tihti saadab teid 200m valesti. Me tabame isiku ukseläve.",
        "em_hero_cta": "Piloot Püsti",
        "em_feat1_title": "Leidmiseks Otse Uksel",
        "em_feat1_desc": "Saada link, mis pin pointib uksi automaatselt, mitte hoonete vahele.",
        "em_feat2_title": "Dispetšeri Kiirlink",
        "em_feat2_desc": "Saada hädalisele SMS Locy lingiga autentsuse tagamaks.",
        "em_feat3_title": "Toimib offline olekuski",
        "em_feat3_desc": "Kasutusvõimalused madalatest ühenduspunktides säästavad elu.",
        "em_steps_title": "Protokollid",
        "em_step1_title": "Väljasta link",
        "em_step1_desc": "Operaator saadab.",
        "em_step2_title": "Asukoht loetud",
        "em_step2_desc": "Hädaabistaja vastab.",
        "em_step3_title": "Kohalejõud",
        "em_step3_desc": "Päästjad suunatud uksele.",
        "rest_hero_sub": "RESTORANIDELE",
        "rest_hero_title": "Kuum Toit. <br><span class=\"text-gradient-red\">Külm Loogika.</span>",
        "rest_hero_desc": "Mitte kunagi enam ei helista kohaletoimetaja kliendile küsitlemaks ukseluku koodi.",
        "rest_hero_cta": "Restorani Demo",
        "rest_feat1_title": "Optimaalne sõit",
        "rest_feat1_desc": "Kuller võtab tellimustšeki foto.",
        "rest_feat2_title": "Trepikoja info",
        "rest_feat2_desc": "Saladused, mida paljad kaardid ei suuda, on integreeritud analüüsi.",
        "rest_feat3_title": "Mootorratta Mugavus",
        "rest_feat3_desc": "Kinnastest ei pea loobuma optimeeritud pikkade nuppude juures.",
        "rest_steps_title": "Töö Protsess",
        "rest_step1_title": "Saada pilt tšekilt",
        "rest_step1_desc": "Asi kiire.",
        "rest_step2_title": "Tark Algoritm",
        "rest_step2_desc": "Nähtud tekst dekrüpteerituna.",
        "rest_step3_title": "Asukoht Valmis",
        "rest_step3_desc": "Marsruudi stardimärk asub kohe WhatsApp rakendusel."
    },
    "it": {
        "comp_hero_sub": "LA NOSTRA MISSIONE",
        "comp_hero_title": "Costruito per l'<span class=\"text-gradient\">Ultimo Miglio.</span>",
        "comp_manifesto": "La logistica ha un problema coi dati continui. Mettendo Locy a punto, superiamo il divario garantendo infrastrutture, e non ulteriori app fastidiose.",
        "comp_val1_title": "Invisibile",
        "comp_val1_desc": "Si trova in WhatsApp senza far scaricare ai fattorini inutili applicazioni.",
        "comp_val2_title": "Istantaneo",
        "comp_val2_desc": "Ogni risultato misurato ai millisecondi minimi per efficienza di tempo.",
        "comp_val3_title": "Sicurezza garantita",
        "comp_val3_desc": "Dati utente eliminati sul colpo (zero-retention) secondo norme altissime.",
        "comp_heri_title": "Nato nell'Estonia Digitale.",
        "comp_heri_desc1": "Creato da <a href=\"https://thinkpoint.ee\" style=\"color: var(--accent-blue); text-decoration: none; font-weight: 600;\">ThinkPoint OÜ</a> (IT, 17131887), Tallinn.",
        "comp_heri_desc2": "GDPR-safe e ultra regolata.",
        "eco_hero_sub": "E-COMMERCE",
        "eco_hero_title": "Buona la prima. <br><span class=\"text-gradient-cyan\">Resi zero.</span>",
        "eco_hero_desc": "Indirizzi falliti minacciano i flussi operativi di ricavi. Locy risana questo difetto.",
        "eco_hero_cta": "Prova",
        "eco_feat1_title": "Meno Restituzioni",
        "eco_feat1_desc": "Il fattorino raggiunge l'utente prima ancora che esca dal deposito corretto.",
        "eco_feat2_title": "Fiducia di Codici a barra",
        "eco_feat2_desc": "Includendo riconoscimento di scansione visiva.",
        "eco_feat3_title": "Sigillo della Prova",
        "eco_feat3_desc": "Il dipendente rileva che il driver è arrivato garantitamente in meta.",
        "eco_steps_title": "Prassi",
        "eco_step1_title": "Scan Label",
        "eco_step1_desc": "Usa fotorivelatore basico.",
        "eco_step2_title": "Controllo Immediato",
        "eco_step2_desc": "Locy risponde localmente.",
        "eco_step3_title": "A destinazione",
        "eco_step3_desc": "Siamo lì.",
        "eco_explore_title": "SCOPRI L'ESCLUSIVA",
        "eco_explore_rest_title": "Ristorazione",
        "eco_explore_rest_desc": "Cibo caldo a target.",
        "eco_explore_emerg_title": "Ambulanze",
        "eco_explore_emerg_desc": "Non indugiano con l'attesa.",
        "eco_cta_title": "Ti affretti ad ottimizzare?",
        "eco_cta_desc": "Senza spendere via carta credito.",
        "em_hero_sub": "PER EMERGENZA",
        "em_hero_title": "Ogni secondo<br><span class=\"text-gradient-alert\">Vale.</span>",
        "em_hero_desc": "GPS normali tradiscono la prospettiva della via reale fino a sgarrare di 100-300m e costando ai paramedici lo stress.",
        "em_hero_cta": "Prova Salvavita",
        "em_feat1_title": "Entrata Mirata",
        "em_feat1_desc": "Diretto accesso alla spilla precisa verso l'esatto marciapiede.",
        "em_feat2_title": "Dispatcher linkato",
        "em_feat2_desc": "Centralino può comunicare inviando url del locator Whatsapp.",
        "em_feat3_title": "Rete Debole compatta",
        "em_feat3_desc": "Nessun grosso carico dati per facilitare urgenze da rinvio banda.",
        "em_steps_title": "Fila logica",
        "em_step1_title": "Invia linkaggio",
        "em_step1_desc": "Avviene in un istante.",
        "em_step2_title": "Toccare il link",
        "em_step2_desc": "Paziente si rivela via GPS.",
        "em_step3_title": "Identificati",
        "em_step3_desc": "Strada fatta.",
        "rest_hero_sub": "IL FOOD",
        "rest_hero_title": "Piatto Rovente. <br><span class=\"text-gradient-red\">Logica Glaciale.</span>",
        "rest_hero_desc": "Fine delle chiamate stressanti da smarrimento della rotta del motorini per palazzine errate.",
        "rest_hero_cta": "Demo di prova online.",
        "rest_feat1_title": "Evita spreco orario",
        "rest_feat1_desc": "Con scontrini convertiti all'instante per navigazione apposita al navigatore integrato in un click.",
        "rest_feat2_title": "Interno appartamento",
        "rest_feat2_desc": "Intercettiamo scale, campanelli dal solo testo dello screenshot utente ai riders.",
        "rest_feat3_title": "Stile Moto-Grip",
        "rest_feat3_desc": "Perfetto per chi ha i guantoni tra i polpastrelli scivolosi.",
        "rest_steps_title": "Guida base",
        "rest_step1_title": "Scatta Scontrino",
        "rest_step1_desc": "Rapido per il bot.",
        "rest_step2_title": "Analisi Immediata",
        "rest_step2_desc": "In due nanosecondi pervenuti.",
        "rest_step3_title": "Partenza",
        "rest_step3_desc": "Verso clienti felici."
    }
}

with open("C:/Users/Mahir/Desktop/Locy/locales/translations.js", "r", encoding="utf-8") as f:
    text = f.read()

for lang, data in new_data.items():
    search_str = f'"{lang}": {{'
    keys_str = ""
    for k, v in data.items():
        keys_str += f'        "{k}": {json.dumps(v)},\n'
    replace_str = f'"{lang}": {{\n' + keys_str
    text = text.replace(search_str, replace_str, 1)

with open("C:/Users/Mahir/Desktop/Locy/locales/translations.js", "w", encoding="utf-8") as f:
    f.write(text)

print("Patch 4 done!")
